### ISSUE TITLE
Input Input Reaction Requirement Additional Requirement Parts

### ISSUE THREAD

**Issue by azriel91** [azriel91/autexousious#150]
In GitLab by @azriel91 on Jul 30, 2019, 09:21

Further decrease hard coded input transitions into default configuration.

Two possible models:

* [ ] Repeat while input is some.

    ```toml
    [transitions]
    # { run_counter = "decreasing" }
    press_x = { next = "run", requirement = [{ input = "same" }, { multi_tap = 2 }] }
    hold_x = { next = "run", requirement = [{ input = "same" }] }
    z_axis = { next = "repeat", requirement = [{ input = "some" }] }
    ```

* [x] Go to "stand" when input is none.

    **Note:** This already exists.

    ~~Doesn't work with separate axes checks when both x and z axes need to be checked.~~

    Works if the requirements have a "check both x and z axes".
    But also need to cater for "run" when x axis is double tapped.

Most likely use the first model, it decouples checking both x and z axis inputs as requirements, and further allows extension in case we want to implement different walking sequences for the z axis.

Also, perhaps instead of a `SequenceId` for the `ControlTransition`, take in a new `SequenceTransition` type, analogous to `SequenceEndTransition`, except its effects are immediate (but potentially with a "loop on end" or "continue" variant).
