### ISSUE TITLE
Arbitrary Sequence IDs

### ISSUE THREAD

**Issue by azriel91** [azriel91/autexousious#155]
In GitLab by @azriel91 on Aug 20, 2019, 14:05

Allow objects to have arbitrary sequence IDs. Complexities to consider:

* Referencing arbitrary sequence IDs of other objects (e.g. Spawning)
* Current `Copy` requirement of the `SequenceId` trait.

---

## Scenario

There are many different game object types: `Character`, `Energy`, `Weapon`.
Each of these have different *sequence ID*s -- essentially named states in a finite state machine (FSM).

To a game modder, it would be simpler to define these like the following:

```yaml
sequences:
  stand: # sequence 0
    frames:
      - component_0: { stuff: 123 }
        component_1: { stuff: 'abc' }

      - component_0: { stuff: 456 }
        component_1: { stuff: 'abc' }

  walk: # sequence 1
    frames:
      - component_0: { stuff: 123 }
      - component_0: { stuff: 456 }
        component_2: { sequence_reference: 'stand' }
```

Because it is used with `specs` and other libraries, often *owned* sequence IDs have to be passed around. Instead of using `String`s (possibly within a newtype) and cloning it each time, it would be more efficient to use a `Copy` type.

There are three main goals:

* Sequence IDs are readable + memorable (English, not Rust).
* Sequence IDs can be arbitrarily named -- so I can't simply use an enum with 100000 variants.
* Sequence IDs are `Copy`.

### Potential Solutions

For sequence IDs to be `Copy`, it would be ideal to map the strings to something `Copy` such as a `u32`, and then when deserializing the configuration file, substituting `sequence_reference`s with the `u32`.

* Use `&str` as the sequence ID type

    - `reference`s are `Copy`.
    - But this gets ugly, you need to pass the lifetime *everywhere*, which is a lot of mental / development overhead.

* Double parse all object configuration.

    - First pass maps sequence ID strings to `SequenceId(u32)`s, store this contextual information.
    - Second pass deserializes the full object, using the map built up from the first pass to discover the `SequenceId(u32)`.

    The first pass needs to happen for all objects before beginning the second pass, because an object's `sequence_reference` may reference another object's sequence.

* ??

In terms of an asset loading graph for solution #2, am thinking it would look something like:

1. Read all object files, these are top level assets: `A`.
2. When all `A`s are loaded, the sequence IDs are parsed and mapped. The mappings are asset `B`s.
3. When `B`s are loaded, then we can now load the "multiple sequences of individual-components" as assets. `C`

    This is turning the single sequence of N components into N sequences of one component. Some of the frame components may not be `Copy`, so they may be stored as assets (`D`) and their handles attached to the entities instead.
