### ISSUE TITLE
Controls UI

### ISSUE THREAD

**Issue by azriel91** [azriel91/autexousious#178]
In GitLab by @azriel91 on Oct 22, 2019, 17:10

Display buttons for each controller from `input_config.ron`.

* [x] State with `StateId::ControlSettings`
* [x] Introduce `KeyboardLayout` enum in `control_settings_model` crate.
* [x] `UiType::ControlSettings(ControlDevices)`
* [x] Refactor: Change `SpritePosition`s which changes per sequence, to `PositionInit`, which is per entity.

**Comment by azriel91** [comment]
In GitLab by @azriel91 on Nov 11, 2019, 13:04

`Talchus`:

> that isn't a thing that exists
>
> you can create any layout you want, on at very least linux and windows
>
> if you wanted it to initialize default keyboard bindings or something, I'm not sure what the best solution is
>
> (in that I don't know that there's any crate to abstract over it, because for the most part it is something you should 100% ignore and let the user have proper control over)
>
> doing a picture representation is probably even more of a mess, tbh I wouldn't bother
> (though xkb has a bunch of stuff to generate picture representations of all sorts of keyboards and keymaps, but that part is generally seen as a waste of effort)

`MaulingMonkey`:

> There are OS functions for it... e.g. on windows you'd use GetKeyboardLayout (https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getkeyboardlayout)
>
> As for linux... maybe parse `/etc/default/keyboard` or `setxkbmap -query` or half a bajllion different other things: https://unix.stackexchange.com/questions/12072/how-do-i-get-current-keyboard-layout
> It's also pretty common to try and dodge the problem entirely
>
> relying on OS translation to character events for text input and just providing rebindable keyboard layouts for game input possibly with a few default layouts the user can manually choose
>
> (relying on OS-translated events is also super important for non-keyboard sources of input... like input method editors, or maybe some voice-to-text systems?)
>
> also note there's... weird edge cases with keyboard layouts
>
> e.g. on windows they used to be set per-app
> but are now global as of 8 or 10
>
> also the user may have multiple keyboards plugged in, each with different layouts
>
> For example, they might have a US layout keyboard, and then an official gamepad chatpad from Microsoft hooked up to their XB1 controller
>
> which just so happens to be a bit more international
>
> and is technically a mexican keyboard layout and will do all kinds of characters wrong if you use the US layout
>
> (it's a mess)

`f32::from_bits(zuurr)`:

> also the keyboard layout isn't really the whole story, you can have something with a us layout that reports weird scancodes and such, often if it's from a different locale this happens
>
> like i know a few people in tel aviv and a bunch of small games i made didn't work for them even on us keyboard layout since the scancodes were all different
>
> it's very tricky, either use the os apis or make it configurable

**Comment by azriel91** [comment]
In GitLab by @azriel91 on Nov 11, 2019, 13:13

```yaml
control_settings:
  - name: "Player One"
    controller:
      keyboard:
        up: Key(Up)
        down: Key(Down)
        left: Key(Left)
        right: Key(Right)
        defend: Key(O)
        jump: Key(P)
        attack: Key(LBracket)
        special: Key(RBracket)

  - name: "Player Two"
    controller:
      keyboard:
        up: Key(W)
        down: Key(S)
        left: Key(A)
        right: Key(D)
        defend: Key(Key1)
        jump: Key(Key2)
        attack: Key(Key3)
        special: Key(Key4)

  - name: "Player Three"
    controller:
      keyboard:
        up: Key(Y)
        down: Key(H)
        left: Key(G)
        right: Key(J)
        defend: Key(Key5)
        jump: Key(Key6)
        attack: Key(Key7)
        special: Key(Key8)
```
