### ISSUE TITLE
Configuration Encoded Transitions -- UI and Objects

### ISSUE THREAD

**Issue by azriel91** [azriel91/autexousious#180]
In GitLab by @azriel91 on Oct 23, 2019, 15:43

* [x] Rename `ControlTransitions` to `InputReactions`.
* [x] Restructure `ControlTransition` types to use new structure.

    `config::ControlTransition` is going to be `InputReaction` that encompasses `SequenceTransition`, `Event`, and so on -- the different kinds of reactions.

* [x] Introduce `Left` and `Right` variants to `InputDirection`.
* [x] Update UI sequence configuration to use `input_reactions`

<details>

<summary>character_selection_widget.yaml</summary>

```yaml
---
# character_selection_widget.yaml
sequences:
  inactive:
    next: "repeat"
    input_reactions:
      press_attack:
        next: "character_select"
        event:
          state_id: "character_selection"
          command: "join"
          options:
            controller_id: self

    frames:
      - { wait: 2, sprite: { sheet: 0, index: 0 } }

  character_select:
    next: "repeat"
    input_reactions:
      press_attack:
        next: "confirmed"
        event:
          state_id: "character_selection"
          command: "select"
          options:
            controller_id: self

      press_jump:
        next: "inactive"
        event:
          state_id: "character_selection"
          command: "leave"
          options:
            controller_id: self

      press_x:
        requirement: { direction: "positive" }
        next: "confirmed"
        event:
          state_id: "character_selection"
          command: "switch"
          options:
            controller_id: self
            selection: self_next

    frames:
      - { wait: 2, sprite: { sheet: 0, index: 0 } }

  confirmed:
    next: "repeat"
    input_reactions:
      press_jump:
        next: "character_select"
        event:
          state_id: "character_selection"
          command: "leave"
          options:
            controller_id: self

    frames:
      - { wait: 2, sprite: { sheet: 0, index: 0 } }
```

</details>

<details>

<summary>game_mode_selection_menu_item.yaml</summary>

```yaml
---
# game_mode_selection_menu_item.yaml
sequences:
  inactive:
    next: "repeat"
    frames:
      - { wait: 2, sprite: { sheet: 0, index: 0 } }

  active:
    next: "repeat"
    input_handler:
      press_attack:
        requirement: ~
        next: "selected"
        event:
          state_id: game_mode_selection
          command: confirm
          args: ["start_game"]

      press_z:
        requirement: { direction: "positive" }
        transition: "active_to_inactive"
        event:
          state_id: game_mode_selection
          command: select
          args: ["exit"]

    frames:
      - { wait: 2, sprite: { sheet: 0, index: 0 } }

  active_to_inactive:
    next: "inactive"
    frames:
      - wait: 2
        sprite: { sheet: 0, index: 0 }

  selected:
    next: "none" # or "delete"
    frames:
      - wait: 2
        sprite: { sheet: 0, index: 0 }
```

</details>
